package org.fishlab.codegenius.impl;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import org.fishlab.codegenius.util.Property;

public class CodeGeniusDescrition {
	private List<Property> properties;//主要是让属性按顺序显示
	
	public CodeGeniusDescrition(){
		this.properties =new ArrayList<Property>();
		this.setDefaultProperties();
	}
	
	@SuppressWarnings("deprecation")
	private void setDefaultProperties() {
		this.addProperty("generated by", "CodeGenius");
		this.addProperty("version", "1.0.0 standard");
		this.addProperty("date", new Date().toLocaleString());
		this.addProperty("author", "Black Lotus");
	}

	private void addProperty(String name, String value) {
		this.properties.add(new Property(name,value));
	}

	public List<Property> getProperties() {
		return properties;
	}


}
